name: deploy to lambda
on:
  push:
    branches:
      - main  #desired branch

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Zip files
        run: zip -r function.zip .

      - name: Deploy to Lambda
        uses: einaregilsson/lambda-deploy@v0.1.2
        with:
          function-name: ngos_zios_generate_report  # Lambda function name
          zip-file: function.zip
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # AWS region
