name: deploy to lambda
on:
  push:
    branches:
      - main  # desired branch

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12  # desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Zip files
        run: zip -r function.zip ngos_zios_generate_report.py

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ngos_zios_generate_report \
            --zip-file fileb://function.zip \
            --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
